export const languages = [
    { title: "Hindi" },
    { title: "English" },
    { title: "Sanskrit" },
    { title: "Marathi" },
    { title: "Gujarati" },
    { title: "Punjabi" },
    { title: "Bengali" },
    { title: "Tamil" },
    { title: "Telugu" },
    { title: "Kannada" },
    { title: "Malayalam" },
    { title: "Assamese" },
    { title: "Odia" },
    { title: "Urdu" },
    { title: "Maithili" },
    { title: "Konkani" },
    { title: "Rajasthani" },
    { title: "Bhojpuri" },
    { title: "Sindhi" },
    { title: "Tulu" },
    { title: "Dogri" },
    { title: "Manipuri" },
    { title: "Bodo" },
    { title: "Santali" },
    { title: "Kashmiri" },
    { title: "Nepali" },
    { title: "Arabic" },
    { title: "Persian" },
    { title: "French" },
    { title: "German" },
    { title: "Spanish" },
    { title: "Other Please Specify" }
  ];
  